### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by Vonnie0709** [guoxiaoxing/phoenix#12]
能否提供混淆处理方式

我处理之后还会出现4.0版本兼容问题

**Comment by guoxiaoxing** [comment]
能说明下具体问题吗，其实如果有问题，可以整体keep的，因为这个库都是UI界面。

-keep class com.guoxiaoxing.phoenix.** { *; }

**Comment by 2414093901** [comment]
我按照你demo里的phoenix-ui中的混淆规则,出现打包无法加载播放视频的问题
