### ISSUE TITLE
videoFilterTime()设置的时间有小bug

### ISSUE THREAD

**Issue by huzipiaopiao** [guoxiaoxing/phoenix#14]
设置了限制视频的时间，但是大于这个时间的视频还是会显示出来，能看下是什么问题吗，不怎么懂Kotlin，看到MediaLoader里就看不懂了，知道时间传进去了，但是不知道在哪儿用到了

**Comment by guoxiaoxing** [comment]
感谢反馈，新版[![Download](https://api.bintray.com/packages/guoxiaoxing/maven/phoenix/images/download.svg)](https://bintray.com/guoxiaoxing/maven/phoenix/_latestVersion)已修复。
