### ISSUE TITLE
可以增加一个限制大小的方法吗

### ISSUE THREAD

**Issue by huzipiaopiao** [guoxiaoxing/phoenix#17]
可以增加一个只显示多少M以下的图片或视频的方法吗

**Comment by guoxiaoxing** [comment]
好的

**Comment by guoxiaoxing** [comment]
更新至新版本

[![Download](https://api.bintray.com/packages/guoxiaoxing/maven/phoenix/allList/download.svg)](https://bintray.com/guoxiaoxing/maven/phoenix/_latestVersion)

```java
   Phoenix.with()
                 .mediaFilterSize(10000)//显示多少kb以下的图片/视频，默认为0，表示不限制
```
