### ISSUE TITLE
压缩问题

### ISSUE THREAD

**Issue by hudan2714** [guoxiaoxing/phoenix#2]
请问压缩效率怎样？能否实现超过1M的图片，才进行压缩？而不是直接把图片压缩图片宽高。

**Comment by guoxiaoxing** [comment]
压缩效率可以，比方说小米手机上拍完的照片是4M，压缩140KB，目前没有提供入口指定压缩阈值的配置，后续会添加。最近在做压缩部分的改造，图片部分提供更多的配置，视频部分改换ffmpeg进行压缩，提高压缩的质量和各机型上的兼容性。

**Comment by hudan2714** [comment]
期待作者能尽快推进能支持大小的压缩。。根据图片大小压缩的功能很实用。。。最近在也需要使用，感谢作者的奉献了。。。图片压缩可以借鉴luban的压缩，使用效果还是不错的。。

**Comment by guoxiaoxing** [comment]
最迟下周一会发出新版，图片压缩借鉴了Luban的思路，后续也会出文章分析Android平台压缩图片各种方案的思路。

**Comment by guoxiaoxing** [comment]
新版已发，公司来了紧急任务，拖更了T_T

//图片/视频选择、预览、编辑与拍照
compile 'com.github.guoxiaoxing:phoenix:1.0.3'

//选填 - 图片压缩，开启功能：Phoenix.with().enableCompress(true)，获取结果：MediaEntity.getCompressPath()
compile 'com.github.guoxiaoxing:phoenix-compress-picture:1.0.3'

//选填 - 视频压缩，开启功能：Phoenix.with().enableCompress(true)，获取结果：MediaEntity.getCompressPath()
compile 'com.github.guoxiaoxing:phoenix-compress-video:1.0.3'
