### ISSUE TITLE
千万编译无法通过

### ISSUE THREAD

**Issue by hudan2714** [guoxiaoxing/phoenix#3]
引入了包，结果编译不通过了
is also present at [com.github.guoxiaoxing.phoenix:phoenix-ui:0.0.13] AndroidManifest.xml:35:17-51 value=(@xml/file_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

应该是资源相冲突了，还望后续版本中，能调整。。感谢！

**Comment by guoxiaoxing** [comment]
可以在
1. 在manifest节点加上：xmlns:tools="http://schemas.android.com/tools"
2. 在application 节点加上：'tools:replace="android:resource"'
来解决这个问题，另外，可以观察下是什么资源冲突了。

最迟下周一会发新版，做以下改造：
1 抽离图片加载接口，改有外部提供。
2 增加视频软解压缩方案，提供更好的平台兼容性和视频清晰度。
