### ISSUE TITLE
你好，是不是没有实现录制完视频压缩呢

### ISSUE THREAD

**Issue by RamboMing** [guoxiaoxing/phoenix#30]
你好，因为含kotlin下载后没能编译成功，看了一下代码好像没有实现视频录制完成就压缩？是这样吗？
还有查询本地图片上视频的代码在哪呢，没找着

**Comment by guoxiaoxing** [comment]
Phoenix对图片/视频的处理是一个管道设计，设置enableCompress(true)就会开启压缩。查询媒体数据库的类是MediaLoader。
