### ISSUE TITLE
有没有Java版本的？能否将图片选择和编辑分成两个库？

### ISSUE THREAD

**Issue by pangli** [guoxiaoxing/phoenix#43]
因为项目需要只需要图片编辑里面的涂鸦功能，想剪裁部分功能

**Comment by guoxiaoxing** [comment]
暂时没有Java版的，是需要单独的Java版图片选择库可以使用知乎的这个：https://github.com/zhihu/Matisse

**Comment by pangli** [comment]
你理解错了，我想单独要图片编辑涂鸦那一块！！！！

**Comment by guoxiaoxing** [comment]
这个暂时没有。
