### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by yz1309** [guoxiaoxing/phoenix#7]
android.database.sqlite.SQLiteException: no such column: duration (code 1): , while compiling: SELECT _id, _data, _display_name, date_added, mime_type, _size, duration, width, height, latitude, longitude FROM images_no_locked as images WHERE ((is_drm=0 OR is_drm IS NULL)) AND ((mime_type=? or mime_type=? or mime_type=?) AND width>0) ORDER BY _id DESC

**Comment by yz1309** [comment]
![1111](https://user-images.githubusercontent.com/6505355/33106100-97a6be8e-cf6b-11e7-8596-642d525962ad.png)

**Comment by yz1309** [comment]
@Override
    public void onaddMedia() {
        Phoenix.with()
                .theme(PhoenixOption.THEME_DEFAULT)// 主题
                .fileType(MimeType.ofImage())//显示的文件类型图片、视频、图片和视频
                .maxPickNumber(10)// 最大选择数量
                .minPickNumber(0)// 最小选择数量
                .spanCount(4)// 每行显示个数
                .enablePreview(true)// 是否开启预览
                .enableCamera(true)// 是否开启拍照
                .enableAnimation(true)// 选择界面图片点击效果
                .enableCompress(true)// 是否开启压缩
                .compressPictureFilterSize(1024)//多少kb以下的图片不压缩
                .compressVideoFilterSize(2018)//多少kb以下的视频不压缩
                .thumbnailHeight(160)// 选择界面图片高度
                .thumbnailWidth(160)// 选择界面图片宽度
                .enableClickSound(false)// 是否开启点击声音
                .pickedMediaList(mMediaAdapter.getData())// 已选图片数据
                .videoFilterTime(0)//显示多少秒以内的视频
                .start(MainActivity.this, PhoenixOption.TYPE_PICK_MEDIA, REQUEST_CODE);
    }

**Comment by guoxiaoxing** [comment]
数据库字段兼容性的问题，我看一下。

**Comment by yz1309** [comment]
发布下新版本吧
//图片/视频选择、预览、编辑与拍照
compile 'com.github.guoxiaoxing:phoenix:1.0.1'

**Comment by guoxiaoxing** [comment]
新版本已发

//图片/视频选择、预览、编辑与拍照
compile 'com.github.guoxiaoxing:phoenix:1.0.2'

//选填 - 图片压缩，开启功能：Phoenix.with().enableCompress(true)，获取结果：MediaEntity.getCompressPath()
compile 'com.github.guoxiaoxing:phoenix-compress-picture:1.0.2'

//选填 - 视频压缩，开启功能：Phoenix.with().enableCompress(true)，获取结果：MediaEntity.getCompressPath()
compile 'com.github.guoxiaoxing:phoenix-compress-video:1.0.2'

视频压缩库还在jcenter审核，如果用不到视频，添加前面的两个依赖即可。

**Comment by yz1309** [comment]
![3](https://user-images.githubusercontent.com/6505355/33126216-aa4677e8-cfbe-11e7-89e3-75362181f07b.png)

**Comment by guoxiaoxing** [comment]
大兄弟咱明天过来了再看行不，我这边复现不了你这个问题。T_T

**Comment by yz1309** [comment]
好的！

**Comment by guoxiaoxing** [comment]
手动比心，哈哈，我要肥家看行尸走肉了。

**Comment by guoxiaoxing** [comment]
//图片/视频选择、预览、编辑与拍照
compile 'com.github.guoxiaoxing:phoenix:1.0.3'

已修复

**Comment by yz1309** [comment]
thanks...
