### ISSUE TITLE
视频压缩问题

### ISSUE THREAD

**Issue by YitouQiongdiaosi** [guoxiaoxing/phoenix#75]
视频压缩的时候有个判断
   if (longer * 9 != shorter * 16) {
            throw new OutputFormatUnavailableException("This video is not 16:9, and is not able to transcode. (" + width + "x" + height + ")");
        }
        if (shorter <= targetShorter) {
            Log.d(TAG, "This video's height is less or equal to " + targetShorter + ", pass-through. (" + width + "x" + height + ")");
            return null;
        }
这个地方为什么要加上这个判断？  不是16:9的视频在压缩的时候会产生什么样的问题？

**Comment by guoxiaoxing** [comment]
目前只支持16:9的，其他视频压缩的时候可能会黑屏。
