### ISSUE TITLE
预览图片是空的

### ISSUE THREAD

**Issue by yz1309** [guoxiaoxing/phoenix#8]
![1](https://user-images.githubusercontent.com/6505355/33165945-74f429c2-d073-11e7-84af-3fabb926fcb9.png)
`mMediaAdapter.setOnItemClickListener(new MediaAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position, View v) {
                if (mMediaAdapter.getData().size() > 0) {
                    //预览
                    Phoenix.with()
                            .pickedMediaList(mMediaAdapter.getData())
                            .start(MainActivity.this, PhoenixOption.TYPE_BROWSER_PICTURE, 0);
                }
            }
        });`

![2](https://user-images.githubusercontent.com/6505355/33165966-91262f96-d073-11e7-971f-1fd1c968eb85.png)

**Comment by guoxiaoxing** [comment]
这个外部预览界面还在开发中，我在考虑要不要和内部的预览界面共用一套，稍后会发出来。

**Comment by yz1309** [comment]
所噶~

**Comment by guoxiaoxing** [comment]
哈哈，你好快~
