### ISSUE TITLE
这个库和 florent37 的 CameraFragment 是什么关系？

### ISSUE THREAD

**Issue by Shouheng88** [guoxiaoxing/phoenix#87]
刚想看下这个库的源码，看了下里面的代码有点眼熟。这个库和 florent37 的 [CameraFragment](https://github.com/florent37/CameraFragment) 是什么关系？

**Comment by guoxiaoxing** [comment]
视频拍照用的这个：https://github.com/florent37/CameraFragment，并做了一些修改。视频压缩用的这个：https://github.com/ypresto/android-transcoder
